### Signup

POST {{base_url}}/users/signup
Content-Type: application/json

{
  "email": "test15@email.com",
  "full_name": "Test14",
  "password": "noufal123",
  "platform": "mobile",
  "username": "test15"
}



### Login

POST {{base_url}}/users/login
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "noufalka123",
  "platform": "mobile"
}

> {%
  var cookieHeader = response.headers.valueOf("Set-Cookie");

  if (cookieHeader) {
      var match = cookieHeader.match(/access_token=([^;]+)/);

      if (match) {
          client.global.set("token", match[1]);
      }
  }
  else{
      client.global.set("token", response.body.access)
      client.global.set("refresh", response.body.refresh)
    }
%}
